#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Los 38 grupos que quedaban: subniveles de gramática pura, donde
generar desde el vocabulario no sirve porque lo que se practica es una
regla, no unas palabras.

Escritos a mano. Se apoyan en formas que ya aparecen en las fichas del
propio subnivel y en vocabulario ya verificado; las frases nuevas van
anotadas en docs para la próxima revisión nativa.
"""
import json, os, collections

RAIZ = os.path.expanduser("~/Proyectos/euskaraz")
D = os.path.join(RAIZ, "data/unidades-v2")


def op(preg, ops, ok, exp):
    assert 0 <= ok < len(ops), preg
    assert len(set(ops)) == len(ops), f"opciones repetidas: {preg}"
    return dict(tipo="opcion", instruccion="Elige la opción correcta",
                pregunta=preg, opciones=list(ops), correcta=ok, explicacion=exp)


def par(inst, ps):
    assert len(ps) == 4, inst
    assert len({a for a, _ in ps}) == 4 and len({b for _, b in ps}) == 4, inst
    return dict(tipo="pares", instruccion=inst,
                pares=[dict(eu=a, es=b) for a, b in ps])


def orden(es, eu, pal):
    assert " ".join(pal) == eu, eu
    return dict(tipo="orden", instruccion="Ordena las palabras", es=es, eu=eu,
                palabras=list(pal))


def G(*vs):
    assert len(vs) == 5, f"grupo con {len(vs)} variantes"
    return list(vs)


# ═══════ 1.3 · Pronunciación y dialectos ═══════
S13 = [
 G(op("La «h» en euskera…", ["suena como una jota", "es muda", "suena como una g", "no existe"], 1,
      "No se pronuncia. «Mahaia» suena «maaia»."),
   op("La «z» del euskera se pronuncia…", ["como la z española", "como una s sibilante",
                                           "como una ch", "como una j"], 1,
      "Una s silbante, apoyando la lengua arriba."),
   op("En Bizkaia, «jan» (comer) suena…", ["«jan» con jota fuerte", "«yan»", "«chan»", "«san»"], 1,
      "La jota fuerte es cosa guipuzcoana."),
   op("¿Qué es el «batua»?", ["un dialecto de Bilbao", "el euskera unificado",
                              "el euskera antiguo", "una región"], 1,
      "El estándar. Es lo que enseña esta app."),
   op("«Zelan?» es la forma vizcaína de…", ["nor?", "nola?", "non?", "zer?"], 1,
      "El «¿cómo?» del bizkaiera.")),
 G(op("La «tx» suena como…", ["la ch española", "la j española", "la s", "la z"], 0,
      "Txakurra se lee «chakurra»."),
   op("¿Cuál de estas NO es una forma vizcaína?", ["zelan", "holan", "nola", "zagoz"], 2,
      "«Nola» es batua; su versión de aquí es «zelan»."),
   op("¿Para qué sirve saber el dialecto de tu zona?",
      ["Para los exámenes", "Para entender lo que oyes por la calle",
       "Para escribir cartas", "Para nada"], 1,
      "Para escribir, batua; para la calle, las notas locales."),
   op("«Aupa» es…", ["adiós", "un saludo informal muy usado en Bizkaia",
                     "por favor", "gracias"], 1,
      "Entre conocidos se oye más que «kaixo»."),
   op("La doble «rr» del euskera se pronuncia…",
      ["floja, casi como una l", "fuerte y vibrante", "muda", "como una d"], 1,
      "Como la rr de «perro».")),
 G(par("cada sonido con su lectura", [("h", "no suena"), ("tx", "como la ch española"),
                                      ("z", "como una s silbante"), ("rr", "fuerte y vibrante")]),
   par("las formas de Bizkaia con las de batua", [("zelan", "nola (¿cómo?)"),
                                                  ("holan", "horrela (así)"),
                                                  ("aupa", "kaixo (hola)"),
                                                  ("gero arte", "ikusi arte (hasta luego)")]),
   op("¿Qué se usa para escribir y para los exámenes?",
      ["el dialecto de tu zona", "el batua", "cualquiera", "el castellano"], 1,
      "El batua es el estándar común."),
   op("«Mahaia» (la mesa) se pronuncia…", ["ma-ja-ia", "maaia", "majaia", "ma-ya-ia"], 1,
      "La h es muda: las dos aes seguidas."),
   op("¿En qué se parece el euskera al castellano?",
      ["En el vocabulario", "En casi nada: no son lenguas emparentadas",
       "En la gramática", "En los verbos"], 1,
      "Es una lengua aislada, sin parientes conocidos.")),
 G(op("¿Qué significa que el euskera sea una «lengua aislada»?",
      ["Que solo se habla en un sitio", "Que no tiene parientes conocidos",
       "Que es muy difícil", "Que es muy antigua"], 1,
      "No se le conoce familia lingüística."),
   op("La «s» y la «z» del euskera…", ["suenan igual", "son dos sonidos distintos",
                                       "no existen", "suenan como la ch"], 1,
      "Cuesta al principio, pero se distinguen."),
   op("Si vas a hablar con alguien de Gipuzkoa, ¿te entenderá tu batua?",
      ["No", "Sí, el batua vale en todas partes", "Solo si hablas despacio", "Solo por escrito"], 1,
      "Para eso se creó."),
   par("cada cosa con lo que es", [("batua", "el euskera unificado"),
                                   ("bizkaiera", "el dialecto de Bizkaia"),
                                   ("euskalkia", "un dialecto"),
                                   ("euskara", "la lengua")]),
   op("«Epa!» es…", ["una despedida", "un saludo informal", "una disculpa", "un agradecimiento"], 1,
      "Como «aupa», entre conocidos.")),
]

# ═══════ 3.3 · Demostrativos ═══════
S33 = [
 G(op("«Hau» señala algo…", ["que está cerca de ti", "que está lejos",
                             "que está con quien te escucha", "que no se ve"], 0,
      "Hau = esto, lo que tienes al lado."),
   op("«Hori» señala algo…", ["cerca de ti", "cerca de quien te escucha",
                              "lejos de los dos", "que no existe"], 1,
      "Como el «eso» castellano."),
   op("«Hura» señala algo…", ["cerca de ti", "cerca del otro", "lejos de los dos", "detrás"], 2,
      "Como «aquello»."),
   op("El plural de «hau» es…", ["hauek", "hauak", "hausak", "hauk"], 0,
      "Hau → hauek."),
   op("¿Cuántos grados de distancia distingue el euskera?",
      ["Uno", "Dos", "Tres", "Cuatro"], 2,
      "Hau, hori, hura: aquí, ahí, allí. Igual que el castellano.")),
 G(par("los demostrativos en singular", [("hau", "esto, este"), ("hori", "eso, ese"),
                                         ("hura", "aquello, aquel"), ("bera", "él, ella")]),
   par("los demostrativos en plural", [("hauek", "estos"), ("horiek", "esos"),
                                       ("haiek", "aquellos"), ("hau", "esto")]),
   op("El plural de «hori» es…", ["horiak", "horiek", "horrek", "horrak"], 1, "Hori → horiek."),
   op("El plural de «hura» es…", ["hurak", "huraek", "haiek", "horiek"], 2,
      "Hura → haiek. Ojo, cambia bastante."),
   op("«Haiek» puede significar…", ["solo aquellos", "solo ellos",
                                    "aquellos, y también ellos", "esos"], 2,
      "Sirve de demostrativo y de pronombre personal.")),
 G(op("Señalando un libro que tienes en la mano dirías…", ["hau", "hori", "hura", "haiek"], 0,
      "Lo que está contigo: hau."),
   op("Señalando algo que tiene tu amigo dirías…", ["hau", "hori", "hura", "hauek"], 1,
      "Lo que está con quien te escucha: hori."),
   op("Señalando una montaña a lo lejos dirías…", ["hau", "hori", "hura", "hauek"], 2,
      "Lo lejano para los dos: hura."),
   op("«Hauek» significa…", ["esto", "estos", "esos", "aquellos"], 1, "Plural de hau."),
   op("¿Qué demostrativo ya conocías de la unidad 2?", ["hori", "hura", "hau", "haiek"], 2,
      "«Hau» sale al presentar cosas: «hau nire laguna da».")),
 G(op("«Horiek» significa…", ["estos", "esos", "aquellos", "ellos"], 1, "Plural de hori."),
   op("Ordena de más cerca a más lejos:", ["hau, hori, hura", "hura, hori, hau",
                                           "hori, hau, hura", "hau, hura, hori"], 0,
      "Aquí, ahí, allí."),
   par("cada singular con su plural", [("hau", "hauek"), ("hori", "horiek"),
                                       ("hura", "haiek"), ("bera", "beraiek")]),
   op("En euskera, los demostrativos van…", ["delante del nombre", "detrás del nombre",
                                             "al final de la frase", "no se usan"], 1,
      "Como los adjetivos: «etxe hau», esta casa."),
   op("«Etxe hau» significa…", ["la casa", "esta casa", "esa casa", "aquella casa"], 1,
      "Nombre + demostrativo.")),
]

# ═══════ 3.4 · Exclamativas y apuros ═══════
S34 = [
 G(op("«Hau hotza!» significa…", ["Hace frío", "¡Qué frío!", "¿Tienes frío?", "El frío"], 1,
      "El demostrativo delante hace la exclamación."),
   op("Para exclamar, en euskera se usa…", ["hau + adjetivo", "muy + adjetivo",
                                            "adjetivo solo", "no hay exclamaciones"], 0,
      "«Hau polita!», ¡qué bonito!"),
   op("«Ez dakit» significa…", ["no quiero", "no sé", "no puedo", "no hay"], 1,
      "La frase que más te va a salvar."),
   op("«Agian» significa…", ["siempre", "nunca", "quizás", "ahora"], 2, "Para no comprometerte."),
   op("Si no entiendes algo, ¿qué dices?", ["Ez dakit", "Bai", "Agian", "Oso ondo"], 0,
      "«No sé» vale para casi todo.")),
 G(op("«Hau polita!» significa…", ["Es bonito", "¡Qué bonito!", "¿Es bonito?", "Lo bonito"], 1,
      "Exclamación con hau."),
   par("las frases de apuro", [("ez dakit", "no sé"), ("agian", "quizás"),
                               ("barkatu", "perdón"), ("mesedez", "por favor")]),
   op("¿Cuál usarías para pedir que te repitan algo?",
      ["Barkatu?", "Bai", "Agian", "Ez"], 0,
      "«Barkatu» sirve de perdón y de «¿cómo dices?»."),
   op("«Zer polita den!» es…", ["una pregunta", "una exclamación", "una negación", "un saludo"], 1,
      "Otra forma de exclamar, con «zer»."),
   op("Las exclamativas se construyen con lo que aprendiste en…",
      ["los saludos", "los demostrativos", "los números", "los verbos"], 1,
      "«Hau» es el mismo de «hau, hori, hura».")),
 G(op("Si alguien te habla muy rápido, ¿qué le dices?",
      ["Poliki, mesedez", "Oso ondo", "Bai, bai", "Agur"], 0,
      "«Despacio, por favor». Poliki = despacio."),
   op("«Ez dakit» y «agian» sirven para…",
      ["afirmar con seguridad", "salir de un apuro sin mentir",
       "despedirse", "dar las gracias"], 1,
      "No saber o no estar seguro también se dice."),
   op("«Hau beroa!» significa…", ["Hace calor", "¡Qué calor!", "El calor", "¿Calor?"], 1,
      "Mismo patrón: hau + adjetivo."),
   par("cada apuro con su salida", [("ez dakit", "no lo sé"), ("barkatu", "perdona"),
                                    ("mesedez", "por favor"), ("eskerrik asko", "muchas gracias")]),
   op("¿Qué diferencia hay entre «hau hotza» y «hau hotza!»?",
      ["Ninguna", "La exclamación: la primera describe, la segunda se admira",
       "La segunda es una pregunta", "La primera está mal"], 1,
      "El tono lo cambia todo.")),
 G(op("¿Cuál NO es una frase de apuro útil?", ["ez dakit", "barkatu", "agian", "hamabi"], 3,
      "«Hamabi» es el número doce."),
   op("«Agian» te sirve cuando…", ["estás seguro", "no estás seguro",
                                   "quieres negarte", "te despides"], 1, "Quizás, tal vez."),
   op("Para exclamar «¡qué grande!» dirías…", ["Hau handia!", "Handia hau!",
                                               "Handia da!", "Hau da handia"], 0,
      "Hau + adjetivo."),
   op("Las exclamativas y los demostrativos…",
      ["no tienen nada que ver", "usan la misma palabra: hau",
       "son lo mismo", "se excluyen"], 1,
      "Por eso van seguidos en esta unidad."),
   op("«Poliki» significa…", ["rápido", "despacio", "fuerte", "bajo"], 1,
      "Muy útil para pedir que te hablen más lento.")),
]

# ═══════ 5.4 · «Una» se dice con «bat» ═══════
S54 = [
 G(op("«La mesa blanca» se dice…", ["mahai zuria", "mahai zuri bat",
                                    "mahaia zuria", "bat mahai zuria"], 0,
      "El -a final es «la»."),
   op("«Una mesa blanca» se dice…", ["mahai zuria", "mahai zuri bat",
                                     "bat mahai zuri", "mahaia bat"], 1,
      "Se quita el artículo y se pone «bat» al final."),
   op("¿Dónde va «bat»?", ["delante de todo", "entre el nombre y el adjetivo",
                           "al final del grupo", "da igual"], 2,
      "Mahai zuri bat."),
   op("Al poner «bat», el artículo -a…", ["se queda", "desaparece",
                                          "se dobla", "cambia a -ak"], 1,
      "No conviven: o «-a» o «bat»."),
   op("«Etxe bat» significa…", ["la casa", "una casa", "esta casa", "casas"], 1,
      "Bat = uno, una.")),
 G(op("Si hay dos cosas, cada una lleva…", ["un solo bat al final", "su propio bat",
                                            "ningún bat", "bat al principio"], 1,
      "Mahai zuri bat eta aulki beltz bat."),
   op("«Una casa roja» se dice…", ["etxe gorria", "etxe gorri bat",
                                   "bat etxe gorria", "etxea gorri bat"], 1,
      "Adjetivo, luego bat."),
   op("¿Qué número es «bat»?", ["uno", "dos", "tres", "cero"], 0,
      "Es el mismo «uno» que ya sabes contar."),
   par("distinguir el artículo", [("etxea", "la casa"), ("etxe bat", "una casa"),
                                  ("mahaia", "la mesa"), ("mahai bat", "una mesa")]),
   op("«Gela handi bat» significa…", ["la habitación grande", "una habitación grande",
                                      "las habitaciones grandes", "habitación grande"], 1,
      "Nombre + adjetivo + bat.")),
 G(orden("una mesa blanca", "mahai zuri bat", ["mahai", "zuri", "bat"]),
   orden("la mesa blanca", "mahai zuria", ["mahai", "zuria"]),
   op("El error típico del castellanohablante aquí es…",
      ["poner bat delante", "olvidarse de quitar el -a", "no poner adjetivo", "usar plural"], 1,
      "«Mahaia zuri bat» no existe."),
   op("«Aulki beltz bat» es…", ["la silla negra", "una silla negra",
                                "sillas negras", "esta silla negra"], 1,
      "Silla + negra + una."),
   op("¿Y para decir «unas» o «algunas»?", ["bat", "batzuk", "bata", "batak"], 1,
      "Batzuk es el plural indefinido.")),
 G(op("«Liburu bat» significa…", ["el libro", "un libro", "los libros", "este libro"], 1,
      "Bat detrás del nombre."),
   op("En «etxe gorri bat», ¿qué hace «bat»?",
      ["cuenta cuántas casas hay", "hace de «una»", "señala cuál es", "no hace nada"], 1,
      "Es el artículo indefinido."),
   par("emparejar", [("etxe bat", "una casa"), ("etxea", "la casa"),
                     ("gela bat", "una habitación"), ("gela", "habitación")]),
   op("«Batzuk» significa…", ["uno", "unos, algunos", "todos", "ninguno"], 1,
      "El plural de bat."),
   op("¿Se puede decir «bat etxe»?", ["Sí", "No: bat va detrás", "Solo en plural", "Solo en Bizkaia"], 1,
      "En euskera casi todo va detrás.")),
]

# ═══════ 6.5 · Las fiestas del año ═══════
S65 = [
 G(op("«Gabonak» significa…", ["buenas noches", "la Navidad", "el año nuevo", "las vacaciones"], 1,
      "Es el plural de «gabon»."),
   op("Si alguien te dice «Gabon» por la noche…", ["te felicita la Navidad",
                                                   "te da las buenas noches",
                                                   "se despide para siempre", "te invita"], 1,
      "Singular: buenas noches. Plural: Navidad."),
   op("¿Quién trae los regalos en Navidad en Euskal Herria?",
      ["Papá Noel", "Olentzero", "los Reyes", "nadie"], 1,
      "Un carbonero que baja del monte en Nochebuena."),
   op("«Inauteriak» son…", ["la Navidad", "los carnavales", "la Semana Santa", "las vacaciones"], 1,
      "En Bizkaia se dice también «Aratusteak»."),
   op("«Urte Berri» significa…", ["Navidad", "Año Nuevo", "cumpleaños", "verano"], 1,
      "Urte (año) + berri (nuevo).")),
 G(par("las fiestas", [("Gabonak", "la Navidad"), ("Urte Berri", "el Año Nuevo"),
                       ("Inauteriak", "los carnavales"), ("Aste Santua", "la Semana Santa")]),
   par("distinguir lo parecido", [("gabon", "buenas noches"), ("Gabonak", "la Navidad"),
                                  ("jaiak", "las fiestas"), ("jaieguna", "el día festivo")]),
   op("«Olentzero» en el diccionario aparece como…",
      ["un personaje", "el día de Nochebuena", "una fiesta de verano", "un monte"], 1,
      "El nombre designaba primero el día; en el habla es el personaje."),
   op("¿Qué relación hay entre «gabon» y «Gabonak»?",
      ["Ninguna", "Gabonak es el plural de gabon", "Son sinónimos", "Una es de Bizkaia"], 1,
      "Las noches buenas del año."),
   op("«Jaiegun» significa…", ["cumpleaños", "día festivo", "fin de semana", "vacaciones"], 1,
      "Jai (fiesta) + egun (día).")),
 G(op("En Bizkaia, a los carnavales se les llama…", ["Inauteriak", "Aratusteak",
                                                     "Gabonak", "Jaiak"], 1,
      "Aratusteak es la forma de aquí."),
   op("«Aste Santua» es…", ["la semana grande", "la Semana Santa",
                            "la primera semana", "la última semana"], 1,
      "Aste (semana) + santu (santo)."),
   op("La «Aste Nagusia» de Bilbao es…", ["la Semana Santa", "la Semana Grande, en agosto",
                                          "la Navidad", "el carnaval"], 1,
      "Nagusi = principal, mayor."),
   par("cada fiesta con su mes", [("Gabonak", "diciembre"), ("Urte Berri", "enero"),
                                  ("Inauteriak", "febrero"), ("Aste Nagusia", "agosto")]),
   op("¿Cuál de estas NO es una fiesta?", ["Gabonak", "Inauteriak", "hilabetea", "Urte Berri"], 2,
      "«Hilabetea» es el mes.")),
 G(op("Para felicitar cualquier cosa se dice…", ["Zorionak!", "Gabon!", "Agur!", "Kaixo!"], 0,
      "Vale para cumpleaños, Navidad y todo lo demás."),
   op("«Zorionak zuri!» se usa sobre todo para…",
      ["despedirse", "felicitar el cumpleaños", "dar las gracias", "brindar"], 1,
      "Es la fórmula habitual."),
   op("«Oporrak» significa…", ["las fiestas", "las vacaciones", "los días", "el verano"], 1,
      "Va siempre en plural."),
   op("¿En qué se parecen «Gabonak», «Inauteriak» y «oporrak»?",
      ["Son del mismo mes", "Van todas en plural", "Son verbos", "Son de Bizkaia"], 1,
      "La -ak final: en euskera muchas fiestas van en plural."),
   par("emparejar", [("Olentzero", "el carbonero de Navidad"), ("Gabonak", "la Navidad"),
                     ("oporrak", "las vacaciones"), ("jaiak", "las fiestas")])),
]

# ═══════ 7.2 · Negar ═══════
S72 = [
 G(op("«No como pan» se dice…", ["Ez ogia jaten dut", "Ez dut ogia jaten",
                                 "Ogia ez jaten dut", "Ogia jaten ez dut"], 1,
      "El «ez» va delante y el auxiliar salta detrás de él."),
   op("Al negar, el auxiliar…", ["se queda donde estaba", "salta justo detrás de «ez»",
                                 "desaparece", "va al final"], 1,
      "Es el cambio que más cuesta al principio."),
   op("«Ez dut» significa…", ["tengo", "no tengo", "no soy", "no hay"], 1,
      "Ez + dut."),
   op("«Ez naiz» significa…", ["no tengo", "no soy / no estoy", "no quiero", "no voy"], 1,
      "La negación de «naiz»."),
   op("¿Qué se pone para negar?", ["ez", "ezer", "inor", "batere"], 0,
      "«Ez» delante del auxiliar.")),
 G(op("«Ez dut ezer nahi» significa…", ["Quiero algo", "No quiero nada",
                                        "No quiero", "Quiero todo"], 1,
      "Ezer = nada, en frase negativa."),
   op("En negativo, «algo de pan» se convierte en…", ["ogia", "ogirik", "ogiak", "ogiaren"], 1,
      "El partitivo -(r)ik aparece al negar."),
   op("«Ez dut dirurik» significa…", ["Tengo dinero", "No tengo (nada de) dinero",
                                      "Quiero dinero", "El dinero no"], 1,
      "Dirua → dirurik en negativo."),
   op("El partitivo -(r)ik sale sobre todo en frases…",
      ["afirmativas", "negativas", "interrogativas", "de pasado"], 1,
      "Y en preguntas: «ba al duzu dirurik?»"),
   op("«Ezer ez» significa…", ["algo", "nada", "todo", "alguien"], 1, "Nada de nada.")),
 G(orden("No como pan.", "Ez dut ogia jaten.", ["Ez", "dut", "ogia", "jaten."]),
   op("¿Dónde va «ez» en la frase?", ["al final", "delante del auxiliar",
                                      "detrás del verbo", "donde quieras"], 1,
      "Y arrastra el auxiliar con él."),
   op("«Ez dakit» es la negación de…", ["dut", "dakit (sé)", "naiz", "dago"], 1,
      "No sé."),
   par("afirmar y negar", [("dut", "tengo"), ("ez dut", "no tengo"),
                           ("naiz", "soy"), ("ez naiz", "no soy")]),
   op("Si el objeto es plural, «no los como» sería…",
      ["ez dut jaten", "ez ditut jaten", "ez naiz jaten", "ez dago jaten"], 1,
      "Ditut para plural, también al negar.")),
 G(op("«Zuk ez duzu haragia jaten» significa…",
      ["Tú comes carne", "Tú no comes carne", "No hay carne", "Quieres carne"], 1,
      "Negación en segunda persona."),
   op("¿Cuál está bien escrita?", ["Ez dut nahi ezer", "Ez dut ezer nahi",
                                   "Ezer ez dut nahi bat", "Nahi ez dut ezer"], 1,
      "El orden habitual."),
   op("El partitivo se pone…", ["delante de la palabra", "como terminación -(r)ik",
                                "con un guion", "no se pone"], 1,
      "Ogia → ogirik."),
   op("«Ez» se puede usar solo, como respuesta?",
      ["No", "Sí: significa «no»", "Solo con verbo", "Solo en preguntas"], 1,
      "Es el «no» de toda la vida, que ya conoces de la unidad 1."),
   orden("No tengo dinero.", "Ez dut dirurik.", ["Ez", "dut", "dirurik."])),
]

# ═══════ 7.4 · «Estoy haciéndolo» ═══════
S74 = [
 G(op("«Estoy comiendo» se dice…", ["jaten dut", "jaten ari naiz", "jaten naiz", "jaten ari dut"], 1,
      "Verbo en -t(z)en + ari + izan."),
   op("Con «ari», el auxiliar siempre es…", ["dut", "izan (naiz/zara/da)", "dago", "daukat"], 1,
      "Aunque haya objeto."),
   op("«Ikasten ari da» significa…", ["estudia", "está estudiando", "estudió", "estudiará"], 1,
      "Tercera persona, ahora mismo."),
   op("«Zer egiten ari zara?» pregunta por…", ["tu trabajo", "lo que haces ahora",
                                               "tus planes", "tu rutina"], 1,
      "Este momento."),
   op("La diferencia entre «jaten dut» y «jaten ari naiz» es…",
      ["ninguna", "lo habitual frente a lo de ahora mismo",
       "singular y plural", "presente y pasado"], 1,
      "Como «como» y «estoy comiendo».")),
 G(par("el presente continuo", [("ari naiz", "estoy"), ("ari zara", "estás"),
                                ("ari da", "está"), ("ari gara", "estamos")]),
   orden("Estoy estudiando.", "Ikasten ari naiz.", ["Ikasten", "ari", "naiz."]),
   op("Para decir «trabajo en Bilbao» (tu empleo) usarías…",
      ["Bilbon lan egiten dut", "Bilbon lan egiten ari naiz",
       "Bilbon lan ari naiz", "Bilbon lan naiz"], 0,
      "Es lo habitual, no lo de ahora."),
   op("«Euria ari du» significa…", ["Llueve mucho", "Está lloviendo", "Llovió", "Va a llover"], 1,
      "Con el tiempo atmosférico también se usa «ari»."),
   op("¿Dónde va «ari»?", ["al principio", "entre el verbo y el auxiliar",
                           "al final", "delante del verbo"], 1,
      "Jaten ari naiz.")),
 G(op("«Zer ari zara egiten?» y «Zer egiten ari zara?»…",
      ["significan cosas distintas", "las dos valen y significan lo mismo",
       "una está mal", "son de dialectos distintos"], 1,
      "El orden admite las dos."),
   op("«Ari naiz» sin verbo delante significa…", ["estoy", "estoy en ello", "soy", "voy"], 1,
      "Se sobreentiende lo que estás haciendo."),
   op("¿Cuál describe una costumbre?", ["Kafea edaten ari naiz", "Kafea edaten dut",
                                        "Kafea ari naiz", "Kafea naiz"], 1,
      "Sin «ari»: lo que haces normalmente."),
   par("distinguir", [("jaten dut", "como (normalmente)"),
                      ("jaten ari naiz", "estoy comiendo"),
                      ("ikasten dut", "estudio"),
                      ("ikasten ari naiz", "estoy estudiando")]),
   orden("Estoy aprendiendo euskera.", "Euskara ikasten ari naiz.",
         ["Euskara", "ikasten", "ari", "naiz."])),
]

# ═══════ 8.3 · Dar indicaciones ═══════
S83 = [
 G(op("«Hartu ezkerra» significa…", ["Ve a la izquierda", "Coge la izquierda",
                                     "La izquierda", "¿Dónde está la izquierda?"], 1,
      "Hartu: coger, tomar. Es una orden."),
   op("Para dar una orden, la forma más simple del verbo es…",
      ["el verbo tal cual, en su forma de diccionario", "el verbo en -t(z)en",
       "el verbo con -ko", "el verbo con ez"], 0,
      "«Etorri!» = ¡ven! «Hartu!» = ¡coge!"),
   op("«Ezkerrera» significa…", ["a la derecha", "a la izquierda", "recto", "atrás"], 1,
      "Lleva dentro el -ra de movimiento."),
   op("«Eskuinera» significa…", ["a la izquierda", "a la derecha", "arriba", "cerca"], 1,
      "La otra mano."),
   op("«Zuzen» significa…", ["torcido", "recto", "lejos", "despacio"], 1,
      "Sigue recto.")),
 G(op("¿Qué diferencia hay entre «ezkerrean» y «ezkerrera»?",
      ["Ninguna", "«-an» es estar a la izquierda; «-ra» es ir hacia la izquierda",
       "Una es de Bizkaia", "«-ra» está mal"], 1,
      "El -ra siempre marca movimiento."),
   op("«Non dago geltokia?» significa…", ["¿Adónde va la estación?", "¿Dónde está la estación?",
                                          "¿Hay estación?", "La estación está"], 1,
      "Non = dónde."),
   op("«Hemendik gertu dago» significa…", ["Está lejos de aquí", "Está cerca de aquí",
                                           "Viene de aquí", "Va hacia aquí"], 1,
      "Gertu = cerca."),
   op("«Urrun dago?» pregunta…", ["¿está cerca?", "¿está lejos?", "¿dónde está?", "¿cuándo?"], 1,
      "Urrun = lejos."),
   par("las indicaciones", [("zuzen", "recto"), ("ezkerrera", "a la izquierda"),
                            ("eskuinera", "a la derecha"), ("gertu", "cerca")])),
 G(orden("Recto, y luego a la izquierda.", "Zuzen, eta gero ezkerrera.",
         ["Zuzen,", "eta", "gero", "ezkerrera."]),
   op("Para pedir una dirección empiezas por…", ["Barkatu, non dago…?", "Agur",
                                                 "Eskerrik asko", "Bai"], 0,
      "«Perdona, ¿dónde está…?»"),
   op("«Etorri!» es…", ["venir", "¡ven!", "vengo", "vendré"], 1,
      "El verbo solo, como orden."),
   op("«Segi zuzen» significa…", ["Para aquí", "Sigue recto", "Gira", "Vuelve"], 1,
      "Segi: seguir."),
   op("¿Cuándo se usa la forma de orden?", ["para preguntar", "para dar instrucciones",
                                            "para negar", "para el pasado"], 1,
      "Indicaciones, recetas, avisos.")),
 G(op("«Noraino?» pregunta…", ["¿de dónde?", "¿hasta dónde?", "¿por dónde?", "¿adónde?"], 1,
      "Nora + raino: el límite del recorrido."),
   op("«Bilbora arte» significa…", ["desde Bilbao", "hasta Bilbao", "en Bilbao", "por Bilbao"], 1,
      "El final del trayecto."),
   par("las preguntas de camino", [("non?", "¿dónde?"), ("nora?", "¿adónde?"),
                                   ("nondik?", "¿por dónde?"), ("noraino?", "¿hasta dónde?")]),
   op("Si te dicen «ezkerrera» tienes que…", ["girar a la izquierda", "quedarte a la izquierda",
                                              "venir de la izquierda", "mirar a la izquierda"], 0,
      "El -ra es movimiento: hacia allá."),
   op("«Hartu bigarren kalea» significa…", ["La segunda calle", "Coge la segunda calle",
                                            "¿Dónde está la segunda calle?", "Dos calles"], 1,
      "Orden + ordinal: aquí se juntan dos cosas que ya sabes.")),
]

# ═══════ 9.5 · De compras ═══════
S95 = [
 G(op("«Txapeldun» significa…", ["el que vende boinas", "el campeón", "el árbitro", "el jugador"], 1,
      "Literalmente, «el que tiene txapela»."),
   op("«Txapelketa» significa…", ["la boina", "el campeonato", "el equipo", "el premio"], 1,
      "La competición donde se gana la txapela."),
   op("¿De qué palabra salen «txapeldun» y «txapelketa»?",
      ["txapela (la boina)", "txapa", "txalo", "txartela"], 0,
      "Al ganador se le entrega una boina."),
   op("La terminación «-dun» significa…", ["sin", "el que tiene", "el que hace", "pequeño"], 1,
      "Euskalduna: el que tiene el euskera."),
   op("«Euskalduna» y «txapelduna» comparten…", ["la raíz", "la terminación -dun",
                                                 "el significado", "nada"], 1,
      "«El que tiene» algo.")),
 G(op("¿Cuál va siempre en plural?", ["alkandora", "prakak", "gona", "jaka"], 1,
      "Los pantalones, como en castellano."),
   op("«Betaurrekoak» se construye con…", ["begi (ojo) + aurre (delante)",
                                           "bete + urre", "beti + arreta", "beso + aurre"], 0,
      "«Los de delante de los ojos»."),
   op("«Zapatak» significa…", ["camisa", "zapatos", "falda", "chaqueta"], 1, "En plural."),
   par("la ropa", [("alkandora", "la camisa"), ("prakak", "los pantalones"),
                   ("jertsea", "el jersey"), ("gona", "la falda")]),
   op("«Erosi» significa…", ["vender", "comprar", "pagar", "mirar"], 1,
      "Ya lo tenías de la unidad de la rutina.")),
 G(op("«Norentzat da?» pregunta…", ["¿de quién es?", "¿para quién es?",
                                    "¿cuánto es?", "¿dónde está?"], 1,
      "Norentzat: para quién."),
   op("«Nire amarentzat» significa…", ["de mi madre", "para mi madre",
                                       "con mi madre", "a mi madre"], 1,
      "La terminación -entzat."),
   op("Al comprar un regalo, la pregunta clave es…",
      ["Zenbat da?", "Norentzat da?", "Non dago?", "Zer da?"], 1,
      "Para quién es."),
   par("las preguntas de la tienda", [("zenbat da?", "¿cuánto es?"),
                                      ("norentzat?", "¿para quién?"),
                                      ("non dago?", "¿dónde está?"),
                                      ("erosi", "comprar")]),
   op("«Opari» significa…", ["tienda", "regalo", "precio", "bolsa"], 1,
      "Lo que compras para otro.")),
 G(op("«Alkandora zuria erosi dut» significa…",
      ["Compro una camisa blanca", "He comprado una camisa blanca",
       "Quiero una camisa blanca", "Vendo una camisa blanca"], 1,
      "Erosi + dut: pasado reciente."),
   op("En «alkandora zuria», el color va…", ["delante", "detrás", "al final de la frase", "aparte"], 1,
      "Como todos los adjetivos, y con el artículo al final."),
   op("«Saldu» significa…", ["comprar", "vender", "pagar", "guardar"], 1,
      "El contrario de erosi."),
   op("«Txapela» es…", ["una camisa", "una boina", "un abrigo", "un zapato"], 1,
      "La prenda de la que salen campeón y campeonato."),
   par("comprar y vender", [("erosi", "comprar"), ("saldu", "vender"),
                            ("dirua", "el dinero"), ("oparia", "el regalo")])),
]

# ═══════ 10.3 · El futuro ═══════
S103 = [
 G(op("«Mañana iré» se dice…", ["Bihar joan naiz", "Bihar joango naiz",
                                "Bihar joaten naiz", "Bihar joan nintzen"], 1,
      "Joan + go + naiz."),
   op("Para el futuro, al verbo se le añade…", ["-ten", "-ko o -go", "-tu", "nada"], 1,
      "Y el auxiliar no cambia."),
   op("«Egingo dut» significa…", ["hago", "hice", "haré", "estoy haciendo"], 2,
      "Egin + go + dut."),
   op("¿Cuándo se usa «-go» en vez de «-ko»?", ["siempre", "detrás de n o l",
                                                "en preguntas", "en negativo"], 1,
      "Joango, egingo: suena mejor."),
   op("«Ikasiko dut» significa…", ["estudio", "estudié", "estudiaré", "estudiando"], 2,
      "Ikasi + ko + dut.")),
 G(par("los tres tiempos", [("joan nintzen", "fui"), ("joaten naiz", "voy"),
                            ("joango naiz", "iré"), ("joaten ari naiz", "estoy yendo")]),
   orden("¿Qué vas a hacer mañana?", "Zer egingo duzu bihar?",
         ["Zer", "egingo", "duzu", "bihar?"]),
   op("Entre «joaten naiz» y «joango naiz» cambia…", ["el auxiliar",
                                                      "la terminación del verbo",
                                                      "el orden", "nada"], 1,
      "El auxiliar se queda igual."),
   op("«Etorriko da» significa…", ["viene", "vino", "vendrá", "está viniendo"], 2,
      "Etorri + ko + da."),
   op("«Etorkizuna» significa…", ["el pasado", "el futuro", "la costumbre", "el plan"], 1,
      "De «etorri»: lo que está por venir.")),
 G(op("«Bihar Bilbora joango naiz» significa…",
      ["Ayer fui a Bilbao", "Mañana iré a Bilbao",
       "Voy a Bilbao", "Estoy yendo a Bilbao"], 1,
      "Bihar + futuro."),
   op("Para hacer planes con alguien usarías…", ["el pasado", "el futuro",
                                                 "el presente continuo", "el imperativo"], 1,
      "«¿Qué haremos?», «iré»…"),
   op("«Ez dut egingo» significa…", ["no lo hago", "no lo hice", "no lo haré", "no lo hago ahora"], 2,
      "La negación funciona igual, con el futuro detrás."),
   par("emparejar", [("joango naiz", "iré"), ("egingo dut", "haré"),
                     ("etorriko da", "vendrá"), ("ikasiko dut", "estudiaré")]),
   op("¿Qué parte de la frase carga con la persona?",
      ["el verbo", "el auxiliar", "el sujeto", "la terminación -ko"], 1,
      "Naiz, dut, da… El verbo solo cambia de terminación.")),
]


BLOQUES = {
 "01-kaixo.json":     [("1.3", S13)],
 "03-galderak.json":  [("3.3", S33), ("3.4", S34)],
 "05-etxea.json":     [("5.4", S54)],
 "06-egutegia.json":  [("6.5", S65)],
 "07-zer.json":       [("7.2", S72), ("7.4", S74)],
 "08-mugi.json":      [("8.3", S83)],
 "09-gustatzen.json": [("9.5", S95)],
 "10-atzo.json":      [("10.3", S103)],
}


def main():
    total = 0
    for archivo, bloques in BLOQUES.items():
        ruta = os.path.join(D, archivo)
        d = json.load(open(ruta, encoding="utf-8"))
        usados = set()
        for g in d["ejercicios"]:
            try: usados.add(int(g["id"].rsplit("-g", 1)[1]))
            except Exception: pass
        siguiente = max(usados) + 1 if usados else 1
        ce = collections.Counter(g["subnivel"] for g in d["ejercicios"])

        for sub, grupos in bloques:
            faltan = 5 - ce.get(sub, 0)
            for variantes in grupos[:max(0, faltan)]:
                d["ejercicios"].append(dict(id=f"{d['id']}-g{siguiente:02d}",
                                            subnivel=sub, variantes=variantes))
                siguiente += 1
                total += 1
        json.dump(d, open(ruta, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
        open(ruta, "a").write("\n")
        print(f"{archivo:20} → {', '.join(s for s, _ in bloques)}")
    print(f"\n+{total} grupos escritos a mano ({total*5} variantes)")


if __name__ == "__main__":
    main()
